version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # Use RabbitMQ with the management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port for messaging
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default RabbitMQ username
      RABBITMQ_DEFAULT_PASS: password  # Default RabbitMQ password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage

volumes:
  rabbitmq_data:
